# Generated by Django 4.2.28 on 2026-02-05 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='파일')),
                ('file_type', models.CharField(choices=[('excel', '엑셀'), ('image', '이미지'), ('pdf', 'PDF')], max_length=10, verbose_name='파일 유형')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기(bytes)')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 완료일')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, verbose_name='추출된 텍스트')),
                ('metadata', models.JSONField(default=dict, verbose_name='메타데이터')),
                ('structured_data', models.JSONField(default=dict, verbose_name='구조화된 데이터')),
                ('total_pages', models.IntegerField(default=0, verbose_name='총 페이지 수')),
                ('total_rows', models.IntegerField(default=0, verbose_name='총 행 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '추출 데이터',
                'verbose_name_plural': '추출 데이터 목록',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='리포트 제목')),
                ('summary', models.TextField(verbose_name='요약')),
                ('content', models.JSONField(default=dict, verbose_name='리포트 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='documents.document', verbose_name='문서')),
            ],
            options={
                'verbose_name': '리포트',
                'verbose_name_plural': '리포트 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
