# Generated by Django 4.2.28 on 2026-02-25 06:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='프로젝트명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('draft', '초안'), ('analyzing', '분석중'), ('ready', '규칙 확정'), ('merging', '병합중'), ('completed', '완료'), ('failed', '실패')], default='draft', max_length=20, verbose_name='상태')),
                ('column_mapping', models.JSONField(default=dict, help_text='{"원본 열이름": "표준 열이름"} 형식', verbose_name='열 매핑 규칙')),
                ('date_columns', models.JSONField(default=list, help_text='날짜 정규화 대상 열 이름 목록', verbose_name='날짜 열 목록')),
                ('number_columns', models.JSONField(default=list, help_text='숫자 정규화 대상 열 이름 목록', verbose_name='숫자 열 목록')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='분석 결과')),
                ('date_output_format', models.CharField(default='%Y-%m-%d', max_length=50, verbose_name='날짜 출력 포맷')),
                ('merged_file', models.FileField(blank=True, null=True, upload_to='merged/%Y/%m/%d/', verbose_name='병합 결과 파일')),
                ('merge_log', models.JSONField(blank=True, default=dict, verbose_name='병합 로그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_projects', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '병합 프로젝트',
                'verbose_name_plural': '병합 프로젝트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MergeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='merge_sources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='파일')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기(bytes)')),
                ('detected_headers', models.JSONField(default=list, verbose_name='탐지된 헤더')),
                ('header_row_index', models.IntegerField(default=0, verbose_name='헤더 행 인덱스')),
                ('total_rows', models.IntegerField(default=0, verbose_name='총 행 수')),
                ('column_types', models.JSONField(default=dict, verbose_name='열 타입')),
                ('sample_data', models.JSONField(default=list, verbose_name='샘플 데이터')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='분석 완료')),
                ('is_processed', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merge_files', to='documents.document', verbose_name='문서')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.mergeproject', verbose_name='병합 프로젝트')),
            ],
            options={
                'verbose_name': '병합 파일',
                'verbose_name_plural': '병합 파일 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('column_mapping', models.JSONField(default=dict, verbose_name='열 매핑 규칙')),
                ('date_columns', models.JSONField(default=list, verbose_name='날짜 열 목록')),
                ('number_columns', models.JSONField(default=list, verbose_name='숫자 열 목록')),
                ('date_output_format', models.CharField(default='%Y-%m-%d', max_length=50, verbose_name='날짜 출력 포맷')),
                ('custom_aliases', models.JSONField(default=dict, help_text='{"표준명": ["별칭1", "별칭2"]} 형식', verbose_name='커스텀 별칭')),
                ('is_public', models.BooleanField(default=False, help_text='다른 사용자도 사용 가능 여부', verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '매핑 템플릿',
                'verbose_name_plural': '매핑 템플릿 목록',
                'ordering': ['-updated_at'],
            },
        ),
    ]
