# Generated by Django 4.2.28 on 2026-02-26 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_mergeproject_mergefile_columnmappingtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='일정명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('due_date', models.DateField(verbose_name='마감일')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('amount', models.FloatField(blank=True, default=0, verbose_name='납부 금액')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_events', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '세금 일정',
                'verbose_name_plural': '세금 일정 목록',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='거래처명')),
                ('business_number', models.CharField(blank=True, help_text='000-00-00000 형식', max_length=20, verbose_name='사업자번호')),
                ('vendor_type', models.CharField(choices=[('customer', '매출처 (고객)'), ('supplier', '매입처 (거래처)'), ('both', '매출/매입 겸용')], default='supplier', max_length=10, verbose_name='거래처 유형')),
                ('category', models.CharField(blank=True, help_text='주 거래 계정과목', max_length=50, verbose_name='계정과목')),
                ('total_income', models.FloatField(default=0, verbose_name='총 입금액')),
                ('total_expense', models.FloatField(default=0, verbose_name='총 출금액')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='거래 건수')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='담당자명')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처 목록',
                'ordering': ['-transaction_count'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
