# Generated by Django 4.2.28 on 2026-02-27 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_taxevent_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='매칭할 문자열 (적요 또는 거래처명)', max_length=255, verbose_name='패턴')),
                ('match_type', models.CharField(choices=[('exact', '정확히 일치'), ('contains', '포함'), ('vendor', '거래처명')], default='contains', max_length=10, verbose_name='매칭 방식')),
                ('category', models.CharField(max_length=50, verbose_name='계정과목')),
                ('source', models.CharField(default='user', help_text='user=수동수정, auto=자동학습, vendor=거래처기반', max_length=20, verbose_name='생성 출처')),
                ('hit_count', models.IntegerField(default=0, verbose_name='적용 횟수')),
                ('priority', models.IntegerField(default=10, help_text='낮은 숫자가 높은 우선순위 (user=10, vendor=20, auto=30)', verbose_name='우선순위')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '분류 규칙',
                'verbose_name_plural': '분류 규칙 목록',
                'ordering': ['priority', '-hit_count'],
                'unique_together': {('user', 'pattern', 'match_type')},
            },
        ),
    ]
