# Generated by Django 4.2.28 on 2026-03-12 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_classificationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('excel', '엑셀'), ('csv', 'CSV'), ('image', '이미지'), ('pdf', 'PDF')], max_length=10, verbose_name='파일 유형'),
        ),
    ]
