# Generated by Django 4.2.28 on 2026-03-10 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='작업 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('target_url', models.URLField(max_length=500, verbose_name='대상 URL')),
                ('login_required', models.BooleanField(default=False, verbose_name='로그인 필요')),
                ('login_url', models.URLField(blank=True, max_length=500, verbose_name='로그인 URL')),
                ('login_credentials_key', models.CharField(blank=True, help_text='환경변수 또는 시크릿 매니저 키 이름', max_length=100, verbose_name='자격증명 키')),
                ('period_type', models.CharField(choices=[('1d', '1일'), ('7d', '1주일'), ('1m', '1개월'), ('1y', '1년'), ('custom', '사용자 지정')], default='1m', max_length=10, verbose_name='기간 유형')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('steps', models.JSONField(blank=True, default=list, help_text='[{"action":"click","selector":"#btn"}, ...]', verbose_name='실행 스텝')),
                ('download_format', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='xlsx', max_length=20, verbose_name='다운로드 형식')),
                ('download_selector', models.CharField(blank=True, help_text='CSS selector for download button', max_length=300, verbose_name='다운로드 버튼 셀렉터')),
                ('status', models.CharField(choices=[('draft', '초안'), ('ready', '실행 가능'), ('running', '실행 중'), ('success', '성공'), ('failed', '실패')], default='draft', max_length=20, verbose_name='상태')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 실행')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '자동화 작업',
                'verbose_name_plural': '자동화 작업 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('action', models.CharField(choices=[('goto', '페이지 이동'), ('click', '클릭'), ('fill', '입력'), ('select_date', '날짜 선택 (캘린더)'), ('set_period', '기간 버튼 설정'), ('wait', '대기'), ('download', '다운로드 클릭'), ('screenshot', '스크린샷'), ('scroll', '스크롤'), ('select_option', '드롭다운 선택')], max_length=20, verbose_name='액션')),
                ('selector', models.CharField(blank=True, max_length=500, verbose_name='CSS 셀렉터')),
                ('value', models.CharField(blank=True, help_text='입력값, URL, 날짜 등', max_length=500, verbose_name='값')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('wait_after', models.IntegerField(default=500, verbose_name='후속 대기(ms)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_list', to='automation.automationtask', verbose_name='작업')),
            ],
            options={
                'verbose_name': '자동화 스텝',
                'verbose_name_plural': '자동화 스텝 목록',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '실행 중'), ('success', '성공'), ('failed', '실패'), ('cancelled', '취소')], default='running', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='소요시간(ms)')),
                ('log', models.JSONField(blank=True, default=list, verbose_name='실행 로그')),
                ('error_message', models.TextField(blank=True, verbose_name='오류')),
                ('downloaded_file', models.FileField(blank=True, null=True, upload_to='automation/%Y/%m/%d/', verbose_name='다운로드 파일')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='automation/screenshots/%Y/%m/%d/', verbose_name='스크린샷')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationtask', verbose_name='작업')),
            ],
            options={
                'verbose_name': '실행 기록',
                'verbose_name_plural': '실행 기록 목록',
                'ordering': ['-started_at'],
            },
        ),
    ]
